[package]
name = "perseus-app"
version = "0.1.0"
edition = "2021"


[dependencies]
perseus = { version = "0.3.0", features = [ "hydrate" ] }
sycamore = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"